"""
InfrastructureAgent — generates Docker IaC files and runs docker compose.

Phase "plan": Generates all infrastructure files (Dockerfiles, docker-compose.yml,
              README.md, AGENTS.md, .cursorrules, .github/copilot-instructions.md).
Phase "apply": Runs docker compose up --build -d and polls health endpoints,
               returning a detailed apply_result with service status.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

from agents.base_agent import BaseAgent
from models.artifacts import InfrastructureArtifact


AGENTS_MD_TEMPLATE = """# AGENTS.md — Agentic SDLC Pipeline Documentation

## Overview

This project was generated by the **Agentic SDLC** pipeline — a dynamic
LLM-orchestrated software development system. Unlike hardcoded prompt chains,
the orchestrator reads the full pipeline state after every tool call and
decides the next action dynamically.

## Pipeline Agents

| Agent | Role | Output Artifact |
|-------|------|-----------------|
| DiscoveryAgent | Extracts structured requirements from free-form text | `01_discovery_artifact.json` |
| ArchitectureAgent | Designs three-tier system architecture | `02_architecture_artifact.json` |
| SpecAgent | Generates OpenAPI 3.0 YAML + SQL DDL contract | `04_generated_spec_artifact.json` |
| EngineeringAgent | Orchestrates Backend, BFF, and Frontend agents | `03_engineering_artifact.json` |
| BackendAgent | Generates Kotlin Spring Boot backend | `generated/backend/` |
| BffAgent | Generates Kotlin WebFlux BFF | `generated/bff/` |
| FrontendAgent | Generates React + TypeScript frontend | `generated/frontend/` |
| InfrastructureAgent | Generates Dockerfiles + docker-compose + docs | `generated/` |
| ReviewAgent | Security and quality gate (OWASP Top 10) | `04_review_artifact.json` |
| TestingAgent | Spec coverage, live HTTP tests, requirements traceability | `05*_testing_*.json` |

## Available Tools

| Tool | Description |
|------|-------------|
| `shell_exec` | Run shell commands with timeout control |
| `file_read` | Read file contents (truncated at 8000 chars) |
| `file_write` | Write files with auto directory creation |
| `file_patch` | Replace first occurrence of a string in a file |
| `file_list` | List files matching a glob pattern |
| `web_fetch` | Fetch and clean text from a URL |
| `api_call` | Call GitHub, JIRA, Linear, or Slack APIs |
| `delegate_agent` | Run a specialist agent by name |

## Extending the Pipeline

To add a new agent:

1. Create `agents/my_new_agent.py` extending `BaseAgent`
2. Add a system prompt at `prompts/my_new_agent.md`
3. Register in `tools/registry.py` `AGENT_MAP`
4. Update `prompts/orchestrator.md` with routing rules

## Stack

- **Backend**: Kotlin 1.9 + Spring Boot 3.3 + Gradle + JPA + JWT (port 8081)
- **BFF**: Kotlin 1.9 + Spring WebFlux + coroutines (port 8080)
- **Frontend**: React 18 + TypeScript 5 + Vite 5 → Nginx (port 3000)
- **Database**: PostgreSQL (port 5432)

## Roadmap

Future agents planned:
- `DocumentationAgent` — auto-generate API docs and user guides
- `ObservabilityAgent` — add metrics, tracing, and logging config
- `DeploymentAgent` — Kubernetes manifests and Helm charts
- `MigrationAgent` — database migration scripts (Flyway/Liquibase)
- `PerformanceAgent` — load testing and profiling
- `ComplianceAgent` — regulatory compliance checks
- `SecurityScanAgent` — SAST/DAST integration
- `MaintenanceAgent` — dependency updates and tech debt tracking
"""


class InfrastructureAgent(BaseAgent):
    """
    DevOps / infrastructure agent.

    In phase="plan", generates all Docker infrastructure files and supporting
    project documentation. In phase="apply", executes docker compose and
    validates all services reach a healthy state.
    """

    name = "infrastructure"
    prompt_file = "prompts/infrastructure_agent.md"

    async def run(self, context: dict[str, Any]) -> InfrastructureArtifact:
        """
        Generate infrastructure files (plan) or deploy containers (apply).

        Args:
            context: Must contain:
                - engineering (dict): EngineeringArtifact as dict.
                - phase (str): "plan" or "apply".
                - output_dir (str, optional): Override output directory.

        Returns:
            InfrastructureArtifact with generated files and deployment results.
        """
        phase = context.get("phase", "plan")
        engineering = context.get("engineering", {})
        output_dir = context.get("output_dir", self.output_dir)

        if phase == "plan":
            return await self._plan(engineering, output_dir)
        else:
            return await self._apply(context, output_dir)

    async def _plan(
        self, engineering: dict[str, Any], output_dir: str
    ) -> InfrastructureArtifact:
        """
        Generate all Docker IaC files, README, AGENTS.md, and editor config.

        Args:
            engineering: EngineeringArtifact dict for context.
            output_dir:  Root output directory.

        Returns:
            InfrastructureArtifact with phase="plan".
        """
        # Build a service summary from engineering.services (the dynamic blueprint map)
        services_dict = engineering.get("services", {})
        if services_dict:
            service_lines = [
                f"  - {name}: {len(sa.get('files', {}))} source files in generated/{name}/"
                for name, sa in services_dict.items()
            ]
            services_summary = "\n".join(service_lines)
        else:
            services_summary = "  (derive service list from engineering context above)"

        plan_prompt = (
            "Generate Docker infrastructure for a dynamically-generated application.\n\n"
            f"--- ENGINEERING CONTEXT ---\n{json.dumps(engineering, indent=2)[:2000]}\n--- END ---\n\n"
            f"Services to containerise:\n{services_summary}\n\n"
            "Generate (use __PENDING__ for complex files):\n"
            "- docker-compose.yml (all code services + any databases/brokers in the architecture)\n"
            "- A Dockerfile per service (derive path from service name, e.g. backend/Dockerfile)\n"
            "  - JVM services: multi-stage (gradle builder + eclipse-temurin:21-jre runtime)\n"
            "  - Frontend/static: multi-stage (node build + nginx runtime)\n"
            "  - Python/other: appropriate base image\n"
            "- README.md\n"
            "- .cursorrules\n"
            "- .github/copilot-instructions.md\n\n"
            "Requirements:\n"
            "- Use the port each service declares in its blueprint (fall back: 8080, 3000, 5432)\n"
            "- Health check on every service\n"
            "- Named volumes for all stateful stores\n\n"
            "Return JSON: { \"<relative_path>\": \"<content or __PENDING__>\" }"
        )

        files = await self._generate_files(
            plan_prompt=plan_prompt,
            fill_system_hint=(
                "You are generating a Docker infrastructure file. "
                "Output ONLY the raw file content. No markdown fences. "
                "Make it production-quality with proper health checks."
            ),
            max_tokens_plan=4096,
            max_tokens_fill=4096,
        )

        # Always write AGENTS.md from template
        files["AGENTS.md"] = AGENTS_MD_TEMPLATE

        # Write files to disk
        out_base = Path(output_dir) / "generated"
        for rel_path, content in files.items():
            target = out_base / rel_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")

        # Extract health endpoints from docker-compose content
        health_endpoints = {
            "backend": "http://localhost:8081/actuator/health",
            "bff": "http://localhost:8080/actuator/health",
            "frontend": "http://localhost:3000",
        }

        artifact = InfrastructureArtifact(
            phase="plan",
            files=files,
            services=["backend", "bff", "frontend", "postgres"],
            health_endpoints=health_endpoints,
        )
        self._save_artifact(artifact, "06a_infrastructure_plan_artifact.json")
        return artifact

    async def _apply(
        self, context: dict[str, Any], output_dir: str
    ) -> InfrastructureArtifact:
        """
        Run docker compose up --build -d and poll health endpoints.

        Args:
            context:    Full context dict containing plan artifact and config.
            output_dir: Root output directory (contains generated/docker-compose.yml).

        Returns:
            InfrastructureArtifact with phase="apply" and apply_result populated.
        """
        from tools.registry import shell_exec, web_fetch

        generated_dir = str(Path(output_dir) / "generated")

        # Run docker compose up --build -d
        compose_result = await shell_exec(
            command="docker compose up --build -d",
            cwd=generated_dir,
            timeout=300,
        )

        apply_result: dict[str, Any] = {
            "compose_exit_code": compose_result.metadata.get("exit_code", -1),
            "compose_output": compose_result.output[:2000],
            "services": {},
        }

        if not compose_result.success:
            apply_result["error"] = compose_result.error

        # Poll health endpoints
        health_endpoints = context.get(
            "health_endpoints",
            {
                "backend": "http://localhost:8081/actuator/health",
                "bff": "http://localhost:8080/actuator/health",
                "frontend": "http://localhost:3000",
            },
        )

        # Give containers a moment to start
        await asyncio.sleep(10)

        for service, url in health_endpoints.items():
            for _ in range(5):
                result = await web_fetch(url, max_chars=500)
                if result.success:
                    apply_result["services"][service] = {
                        "healthy": True,
                        "url": url,
                        "response": result.output[:200],
                    }
                    break
                await asyncio.sleep(5)
            else:
                apply_result["services"][service] = {
                    "healthy": False,
                    "url": url,
                    "error": "Health check failed after 5 attempts",
                }

        artifact = InfrastructureArtifact(
            phase="apply",
            files={},
            services=list(health_endpoints.keys()),
            health_endpoints=health_endpoints,
            apply_result=apply_result,
        )
        self._save_artifact(artifact, "06b_infrastructure_apply_artifact.json")
        return artifact
